const UI_EN = {
  "本机自动存档": "Saved on this device",
  "本次会话游玩 · 存档不可用": "Session only · Cannot save",
  "RABBIT GUIDE · 简短说明": "RABBIT GUIDE · Brief Guide",
  "跳过引导": "Skip Guide",
  "重新开始本轮故事": "Restart This Story Run",
  "问问九月兔": "Ask Mr Rabbit",
  "重新翻开这个九月？": "Reopen this September?",
  "本轮线索和对话会清空，已抵达的结局将保留。": "All clues and chats for this run will be cleared, unlocked endings remain saved.",
  "确认重新开始": "Confirm Restart",
  " 发来一篇新日记 · 可在聊天中打开": " sent a new diary · Open in chats",
  "回应已记录": "Response recorded",
  " · 本章已完成": " · Chapter completed",
  "先核对完当前章节的经过，再翻到更早的关系和回忆。": "Finish reviewing the events of this chapter first, then unlock earlier relationships and memories.",
  "先与": "First, say hello to ",
  "打个招呼，聊清九月十六日当天的经历，再解锁这一页。": " and ask about September 16 to unlock this page.",
  "先读完已收到的上一页，再和": "Read the previous diary first, then talk to ",
  "聊完对应话题。": " about its topic.",
  "继续与": "Keep talking to ",
  "聊聊这一章的近况，等待对方发来新的回忆。": " about this chapter to receive more memories.",
  "转来 ": "Forwarded ",
  " 则新的校园消息": " new campus updates",
  "消息已收好，有新风声我再发你": "Messages saved. I'll send updates as they come in.",
  "打开新消息 ↗": "Open new message ↗",
  "消息存档 ↗": "Archive ↗",
  "发现线索": "Clues Found",
  "完成追问": "Follow-ups",
  "第四章 · 后来的日子 →": "Chapter 4 · The Days After →",
  "查看本轮结局 →": "View your ending →",
  "打开下一章 →": "Open next chapter →",
  "新章节已打开 · 九月兔转来了新的校园消息": "New chapter opened · Mr Rabbit shared new campus updates",
  "新章节已打开 · 先去对话里和他们继续聊聊": "New chapter opened · Go to Chats to continue talking with them first",
  "整理这段九月 →": "Bring September together →",
  "聊完本章 ": "Follow up on all ",
  " 条线索后，下一页才会打开。": " clues in this chapter to unlock the next one.",
  "人物日记": "Diaries",
  "已收到 ": "Received ",
  " / 28 篇 · 先聊当天，再翻旧事与结局": " / 28 diaries · That day, the past, and what comes next",
  "尚未收到 · 第": "Not received · Page ",
  "页": "",
  "随聊天逐步解锁": "Unlocks gradually as you chat",
  "⌑ 回忆暂未开启": "⌑ Memory not yet accessible",
  "✓ 线索已收录": "✓ Clue collected",
  "○ 新收到 · 等待阅读": "○ Newly received · Pending read",
  " / 尚未寄来的私人手记": " / Unsent Personal Diary",
  "这一页，还没有打开": "This page has not been opened yet",
  "每一篇都从对话中慢慢浮现。现在不会显示标题、正文或线索。": "Every entry emerges gradually from your chats. Titles, content or clues will not be displayed right now.",
  "先读已收到的上一页 →": "Read the previous diary first →",
  "去和": "Chat with ",
  "聊聊 →": " →",
  " / 私人手记": " / Personal Diary",
  " 字 · 私人记录与后记 · 可滚动阅读": " words · Personal diary and later notes · Scroll to read",
  "的长篇日记正文": "'s full diary",
  "后来补记": "Later Addendum",
  "查看线索：": "View clue: ",
  "收集线索：": "Collect clue: ",
  "✓ 这页的线索已记入手帐": "✓ Clues on this page have been saved to your notebook",
  "⌕ 点击带虚线的文字，收录可追问的线索": "⌕ Tap underlined text to save trackable clues",
  "去问问": "Ask ",
  "这页日记还没有收到，先去和对方聊聊": "This diary page has not been received yet. Go chat with them first",
  "新线索「": "New clue “",
  "」已收录 · 可前往对话": "” saved · Go to Chats",
  "这条线索已收录，去对话中追问吧": "This clue is already saved — go follow up in chats",
  "他们的另一面": "Chats",
  "所有聊天均为剧情模拟 · 你的回复会被记住": "All chats are story simulations · Your replies are remembered",
  "九月兔": "Mr Rabbit",
  "异地 · 文字私信": "Remote · Text Messages",
  "首次私信 · 先聊九月十六日当天": "First Message · Start with September 16",
  "09 / 16 · 当天的记录": "09 / 16 · That Day's Records",
  "第 0": "Chapter 0",
  " 章 · ": " · ",
  " 发来私人手记": " sent a personal diary",
  " 字 · ": " words · ",
  "再次翻阅 ↗": "Revisit ↗",
  "打开新收到的日记 ↗": "Open new diary ↗",
  "话题 · ": "Topic · ",
  " 正在输入…": " is typing…",
  "点击下方选项，回复 ": "Tap below to reply to ",
  " · 先和": " · Continue chatting with ",
  "继续聊聊": "",
  "选择回应 · 这句话会影响你们的信任": "Pick a reply · It will affect your trust level",
  "选择一条线索，向 ": "Choose a clue to ask ",
  " 追问": " about",
  "有一篇刚收到的日记，读完再接着聊吧。": "A new diary has arrived. Read it before continuing the conversation.",
  "这段话先聊到这里。也听听其他人记得什么，下一章再继续。": "Let's pause this topic for now. Hear what others remember, and we'll pick up in the next chapter.",
  "打开刚收到的日记 →": "Open the newly received diary →",
  "回到日记手帐 →": "Return to the diary journal →",
  "你与": "Your chat with ",
  "的对话还在等待回应。": " is waiting for a reply.",
  "你": "You",
  "等对方发完这几句，再继续聊吧": "Wait for the other person to finish sending these messages, then continue the chat",
  "本轮已结束，重开后可以重新选择。": "This round has ended. You can make new selections after restarting.",
  "先回应当前话题，再开启下一条线索": "Respond to the current topic first, then unlock the next clue",
  "这页可以回看；新话题先按当前章节的顺序核对。": "You can review this page; check new topics against the current chapter order first.",
  "先完成这一段私信，再继续追问": "Finish this private message thread first, then follow up with more questions",
  "线索手帐": "Clues",
  " 条已发现 · ": " found · ",
  " 条已交流": " discussed",
  "尚未发现的线索": "Undiscovered clue",
  "返回《": "Return to “",
  "》，留意字里行间的细节。": "” and look for details between the lines.",
  "✓ 已交流 · 回看": "✓ Discussed · Review",
  "带着线索去对话 ↗": "Ask about this clue ↗",
  "翻开这页日记 →": "Open this diary page →",
  "提醒：不要把猜测当作事实": "Reminder: Don't treat guesses as facts",
  "单条日记是主观视角。时间、原始录音与检修记录需要相互印证；感情中的误会不等于事件原因。": "A single diary entry is a subjective perspective. Timelines, original recordings, and maintenance records must cross-verify each other; misunderstandings in relationships do not equal the cause of the incident.",
  "人物档案": "People",
  "四个人，四种没有说出口的喜欢": "Four people, four unspoken loves",
  "阅读 ": "Read ",
  " 的结局日记 →": " 's ending diary →",
  " 的日记 →": " 's diary →",
  "已抵达的结局 · ": "Endings Reached · ",
  "等对方这几句发完，再看九月兔的消息": "Wait for the ongoing messages to finish, then check Mr Rabbit's updates",
  "九月兔转来：": "Mr Rabbit: ",
  " 条未读 ↗": " unread ↗",
  "查看九月兔新消息": "View new messages from Mr Rabbit",
  "九月兔消息存档": "Mr Rabbit Message Archive",
  "校园来信": "Campus Letters",
  " 则已收到": " received",
  "● 新消息": "● New",
  "已读 · 可回看": "Read · Revisit Anytime",
  "校园消息 · 剧情内转发": "Campus Messages · Story Forwarded",
  "九月兔转发内容": "Mr Rabbit Forwarded Content",
  "九月兔正在输入…": "Mr Rabbit is typing…",
  "下一条未读（": "Next Unread (",
  "和": "Chat with ",
  "聊聊 ↗": " ↗",
  "回到人物对话 →": "Back to Chats →",
  "聊到相关事情时，九月兔才会发来新消息。已收到的内容留在这里。": "New messages from Mr Rabbit will only arrive when you discuss relevant topics. All received content is kept here.",
  "先完成第三章的结局选择，再读他们后来的故事": "Complete Chapter 3's ending choices first, then read their subsequent stories",
  "等这几句消息发完，再去看后来的日子": "Wait for the ongoing messages to finish, then access The Days After",
  "最后的私信": "Final Messages",
  "结局日记": "Ending Diaries",
  "第四章 · 后来的日子": "Chapter 4 · The Days After",
  " · 四个人各自的后续": " · Each character's follow-up story",
  "已读结局": "Read Epilogue",
  "新日记": "New Diary",
  "⌑ 结局日记": "⌑ Epilogue Diary",
  "下次上线见": "See You Next Time Online",
  "异地 · 只聊近况，不再追问线索": "Long distance · Only talk about recent updates, no more clue questions",
  "的最后私信": "'s final messages",
  "这次聊天之后 · ": "After this chat · ",
  " 的新日记": " 's new diary",
  "打开新日记 ↗": "Open new diary ↗",
  "最后几句话留在了聊天框里。后来，生活又往前走了一点。": "The last few words are left in the chat box. After that, life moves a little further on.",
  "再听听另一位的近况 →": "Hear how the other person is doing →",
  "回复 ": "Reply to ",
  "这一页，写在告别之后": "This page is written after we said goodbye",
  "先和": "Finish your final conversation with ",
  "聊完最后一段私信，再翻开这篇新的日记。": " to unlock this new diary.",
  "继续最后的私信 →": "Continue the final private messages →",
  " 字 · 聊天之后写下的生活 · 私人记录": " words · Life after the conversation · Personal diary",
  "的结局日记": "'s ending diary",
  "✓ 这篇结局日记已读": "✓ This epilogue diary has been read",
  "读到页末，收好这一篇日记": "Read to the end to mark this diary as read",
  "✓ 已读完这篇日记": "✓ Finished reading this diary",
  "收好这篇结局日记 ✓": "Mark this diary as read ✓",
  "回看和": "Review ",
  "的最后私信 →": "'s final messages →",
  "继续看其他人的结局 →": "Continue to others' endings →",
  "事件原因不会随着选择改变。你选择的，是如何对待他们的心事。": "The cause of events does not change with your choices. What you choose is how to treat their hidden thoughts.",
  "进入第四章 · ": "Enter Chapter 4 · ",
  "已收藏此结局。第四章里，四个人还想各自和你聊一会儿；聊完后，可以读到他们新写的结局日记。": "This ending is saved. In Chapter 4, the four people each want to chat with you for a while; after chatting, you can read their newly written ending diaries.",
  "未寄出的九月 · 校园手记": "The September That Was Never Sent · Campus Notes",
  "九": "SEP",
  "月": "T",
  "一 部 可 以 翻 阅 的 青 春": "A STORY TOLD THROUGH DIARIES",
  "未寄出的九月": "The September That Was Never Sent",
  "有些心事，": "Some thoughts",
  "留在了那场雨里。": "were left in that rain.",
  "二十八篇私人日记。一封没有寄出的信。": "28 personal diaries. One unsent letter.",
  "那些没能说出口的话，都留在了九月。": "All the unspoken words were left in September.",
  "校园恋爱 · 文字悬疑": "Campus Romance · Text Mystery",
  "九月兔陪你翻开这一页": "Mr Rabbit is here to help",
  "先聊九月十六日，再随线索回到过去": "Talk about September 16 first, then follow clues back to the past",
  "把没说出口的话，连起来": "Piece together the unspoken words",
  "日记只是一个人的视角，": "A diary only shows one person's perspective,",
  "不是事情的全部。": "not the full story.",
  "找到线索后，去「对话」": "After finding clues, go to \"Chats\"",
  "听听他们没有写下的话。": "to hear the words they didn't write down.",
  "虚构故事 · 所有角色均已成年": "Fictional story · All characters are adults",
  "人物分享的日记节选均已获得授权": "All diary excerpts shared by characters are authorized",
  "我们寻找的，从来不只是一个答案。": "What we are looking for is never just an answer.",
  "原创互动短篇 · 约 60–90 分钟": "Original interactive short story · About 60–90 minutes",
  "知道了": "Got it",
  "未寄出的九月首页": "The September That Was Never Sent Home",
  "玩法说明": "How to Play",
  "重新开始": "Restart",
  "暮色中亮着暖灯的雨后大学校园": "Rain-washed university campus lit with warm lights at dusk",
  "九月兔引导": "Mr Rabbit Guidance",
  "戴绿色围巾、抱着笔记本的九月兔": "Mr Rabbit with a green scarf and a notebook"
};
